### ISSUE TITLE
Debug with hooks again

### ISSUE THREAD

**Issue by michaelcullum** [phpBB-Blog/phpBB-Blog#10]
<code>[phpBB Debug] PHP Notice: in file /includes/hooks/index.php on line 141: call_user_func_array() expects parameter 1 to be a valid callback, function 'phpbb_blog' not found or invalid function name
[phpBB Debug] PHP Notice: in file /includes/functions.php on line 4284: Cannot modify header information - headers already sent by (output started at /includes/functions.php:3493)
[phpBB Debug] PHP Notice: in file /includes/functions.php on line 4286: Cannot modify header information - headers already sent by (output started at /includes/functions.php:3493)
[phpBB Debug] PHP Notice: in file /includes/functions.php on line 4287: Cannot modify header information - headers already sent by (output started at /includes/functions.php:3493)
[phpBB Debug] PHP Notice: in file /includes/functions.php on line 4288: Cannot modify header information - headers already sent by (output started at /includes/functions.php:3493)</code>

is shown on all pages. This line of code is line 66 of the hook file. Instead of displaying it says 1:
        'OVERALL_BLOG_TITLE'    => isset($config['blog_title']),

**Comment by erikfrerejean** [comment]
Has nothing to do with that line ;). You register a non-existing function.

**Comment by michaelcullum** [comment]
I was tired. :P
