### ISSUE TITLE
Support for custom BBCodes

### ISSUE THREAD

**Issue by vinny** [phpBB-Blog/phpBB-Blog#32]
The MOD does not support custom BBCode.

**Comment by vinny** [comment]
PR: https://github.com/phpBB-Blog/phpBB-Blog/pull/33

**Comment by michaelcullum** [comment]
Sorry, only just saw the PR. I'll include this in 1.0.0 as I haven't finished releasing it yet. Thanks vinny. :)

**Comment by michaelcullum** [comment]
Merged

**Comment by michaelcullum** [comment]
It doesn't parse them.

**Comment by michaelcullum** [comment]
I'll give this a quick test.

**Comment by michaelcullum** [comment]
Works. Thanks again marcus.
