### ISSUE TITLE
XHTML Strict invalid

### ISSUE THREAD

**Issue by vinny** [phpBB-Blog/phpBB-Blog#34]
I'm testing the mod and there are lots XHTML errors. As you want submit in next days at MODDB, I'll propose a fix as fast as possible.

**Comment by michaelcullum** [comment]
Ah thanks for pointing that out. I hadn't checked for XHTML or CSS Validation.

I'll hold the 1.0.0 release.

Thanks again. :)

**Comment by michaelcullum** [comment]
By a lot I thought you meant 10 or so. 230 errors for just post article, blog home and view blog entry. Looks like no release for at least a couple of days.

I seriously owe you a favour for this.

@imkingdavid _sighs_

**Comment by imkingdavid** [comment]
Hey, this is old code, when I sucked at writing HTML. ;)

**Comment by michaelcullum** [comment]
I'll post the release once this is done.

**Comment by vinny** [comment]
Part1: https://github.com/mvinny/phpBB-Blog/commit/816b8dd5e659e7a3ed555f0da81a834504b1ba25
Part2: https://github.com/mvinny/phpBB-Blog/commit/006fd34f465cd8aad5c356fcec93a708863ed628

Status:
blog home = ok + 1 error
view article = ok + 1 error
Edit Comment = OK
Edit article = 4~5 errors + 1 error
View Cat = ok + 1 error
View Tag = ok + 1 error

This 1 error on blog home, view article, Edit article, view cat/tag is because the CSS inserted into the <code>blog_index_body.html</code>. I recommend inserting it in a new CSS file and include on the overall_header.html by 
<\* link href="{T_THEME_PATH}/blog.css" rel="stylesheet" type="text/css" media="screen"  */>.

I think that part 3 will be the last. Do you recommend anything about the CSS above?

**Comment by michaelcullum** [comment]
Go ahead. What are the 4~5  errors on edit article?

And did you see my comment about me merging part one and two now using the fork queue?

Thank you.

**Comment by vinny** [comment]
The errors are because some inputs use the same ID.

I think is better to merge when it's all fixed. 

So, what do you think about the new CSS file. Will need to enter via overall_header.htmt in install.xml

**Comment by michaelcullum** [comment]
hm... Looks like we haven't got much choice to be honest as it needs to be XHTML valid to get validated. Unless we put the blog on a completely different header template from the rest of the site?

**Comment by michaelcullum** [comment]
Although we do already have 1 edit in overall_header.html already for the link to the blog.

**Comment by michaelcullum** [comment]
Just to check, are they warnings or errors?

**Comment by vinny** [comment]
Both.

The "+ 1 error" in all pages is:

```
Error Line 155, Column 23: document type does not allow element "style" here

<style type="text/css">

The element named above was found in a context where it is not allowed. This could mean that you have incorrectly nested elements -- such as a "style" element in the "body" section instead of inside "head" -- or two elements that overlap (which is not allowed).

One common cause for this error is the use of XHTML syntax in HTML documents. Due to HTML's rules of implicitly closed elements, this error can create cascading effects. For instance, using XHTML's "self-closing" tags for "meta" and "link" in the "head" section of a HTML document may cause the parser to infer the end of the "head" section and the beginning of the "body" section (where "link" and "meta" are not allowed; hence the reported error).
```

It is the CSS that needs to be moved to <\* head> ....  </*head>

"Edit article = 4~5 errors"
Are in fact 3 Errors and 5 warnings.

```
Error Line 160, Column 56: there is no attribute "name"

<form action="blog.php?action=edit_blog&amp;id=2" name="postform" method="post">



You have used the attribute named above in your document, but the document type you are using does not support that attribute for this element. This error is often caused by incorrect use of the "Strict" document type with a document that uses frames (e.g. you must use the "Transitional" document type to get the "target" attribute), or by using vendor proprietary extensions such as "marginheight" (this is usually fixed by using CSS to achieve the desired effect instead).

This error may also result if the element itself is not supported in the document type you are using, as an undefined element will have no supported attributes; in this case, see the element-undefined error message for further information.

How to fix: check the spelling and case of the element and attribute, (Remember XHTML is all lower-case) and/or check that they are both allowed in the chosen document type, and/or use CSS instead of this attribute. If you received this error when using the <embed> element to incorporate flash media in a Web page, see the FAQ item on valid flash.
Error Line 171, Column 44: ID "subject" already defined

…dd><input type="text" name="desc" id="subject" size="45" maxlength="64" tabind…



An "id" is a unique identifier. Each time this attribute is used in a document it must have a different value. If you are using this attribute as a hook for style sheets it may be more appropriate to use classes (which group elements) than id (which are used to identify exactly one element).
Info Line 167, Column 45: ID "subject" first defined here

…d><input type="text" name="title" id="subject" size="45" maxlength="64" tabind…

Error Line 345, Column 44: ID "subject" already defined

…dd><input type="text" name="tags" id="subject" size="60" maxlength="255" tabin…



An "id" is a unique identifier. Each time this attribute is used in a document it must have a different value. If you are using this attribute as a hook for style sheets it may be more appropriate to use classes (which group elements) than id (which are used to identify exactly one element).
Info Line 167, Column 45: ID "subject" first defined here

…d><input type="text" name="title" id="subject" size="45" maxlength="64" tabind…

Warning Line 166, Column 21: reference to non-existent ID "title"

                <dt><label for="title">Blog Title:</label></dt>



This error can be triggered by:
    A non-existent input, select or textarea element
    A missing id attribute
    A typographical error in the id attribute

Try to check the spelling and case of the id you are referring to.
Warning Line 344, Column 21: reference to non-existent ID "tags"

                <dt><label for="tags">Blog Tags:<br /></label><em>Separate each entry with …



This error can be triggered by:
    A non-existent input, select or textarea element
    A missing id attribute
    A typographical error in the id attribute

Try to check the spelling and case of the id you are referring to.
Warning Line 340, Column 21: reference to non-existent ID "allow_cmnt"

                <dt><label for="allow_cmnt">Allow users to post comments:</label></dt>



This error can be triggered by:
    A non-existent input, select or textarea element
    A missing id attribute
    A typographical error in the id attribute

Try to check the spelling and case of the id you are referring to.
Warning Line 175, Column 21: reference to non-existent ID "cat_id"

                <dt><label for="cat_id">Category:</label></dt>



This error can be triggered by:
    A non-existent input, select or textarea element
    A missing id attribute
    A typographical error in the id attribute

Try to check the spelling and case of the id you are referring to.
Warning Line 170, Column 21: reference to non-existent ID "desc"

                <dt><label for="desc">Description:</label></dt>



This error can be triggered by:
    A non-existent input, select or textarea element
    A missing id attribute
    A typographical error in the id attribute

Try to check the spelling and case of the id you are referring to.
```

**Comment by michaelcullum** [comment]
Your opinion, new header file for blog or overall_header.html edit and make it a 2 edit MOD?

**Comment by vinny** [comment]
To be honest, I think better to create a new CSS file to move the code and edit the overall_header.html to add something like:

<_! IF BLOG_ENABLE --_>
<\* link href="{T_THEME_PATH}/blog.css" rel="stylesheet" type="text/css" media="screen" _/>.
<_!-- ENDIF --*>

**Comment by michaelcullum** [comment]
hm... Ok then, do you want to include that in part 3 then?

**Comment by vinny** [comment]
What do you think? What is your opinion?

I have corrected the other errors, missing only the CSS.

**Comment by michaelcullum** [comment]
I'm not sure. I would like to keep it as few edits as possible but we already edit overall_header.html so its not like opening a second file. Its not a big edit and I suppose this keeps better compatibility with custom styles.

**Comment by vinny** [comment]
So, I do the following: I will send the last part and submit the PR, already fixed all errors only missing CSS.

You decided the best solution to the CSS. :D

**Comment by michaelcullum** [comment]
Thanks. I'll merge the PR then go to bed as its 1:44 and I only stayed up to get this baby finished and released for MODs in Dev Forum tonight.

**Comment by vinny** [comment]
Part3: https://github.com/mvinny/phpBB-Blog/commit/424b998fadf9113d211bd86526783e4b66192080

PR: https://github.com/phpBB-Blog/phpBB-Blog/pull/46

**Comment by michaelcullum** [comment]
Do you want to do the CSS etc. or shall I?

**Comment by vinny** [comment]
I'm also go to bed. If you dont do, I do later, but tell me how you prefer.

And if you need more help with HTML-CSS let me know.

**Comment by michaelcullum** [comment]
If you could it would be greatly appreciated as you know what code needs moving.

**Comment by vinny** [comment]
Okay. How do you prefer to call the CSS file? <code>blog.css</code> or <code>phpbb_blog.css</code> or another name?

Prefer any line in <code>overall_header.html</code>? 

And what is the variable that checks if the blog is active?

**Comment by michaelcullum** [comment]
You've seen more custom styles than I have Marcus. A line with a find less likely to be changed in a custom style. ;)

blog.css please

Erm, good question. BLOG_ENABLED_C now. But I only just committed it so you'll need to merge from the repo.

**Comment by vinny** [comment]
Check this: https://github.com/mvinny/phpBB-Blog/commit/83d506d3357dd818c49e5a0dcf5e38c866977672

**Comment by michaelcullum** [comment]
Looks good. Submit a PR and I'll merge it.

**Comment by michaelcullum** [comment]
Merged
