### ISSUE TITLE
SVN file structure

### ISSUE THREAD

**Issue by erikfrerejean** [phpBB-Blog/phpBB-Blog#38]
The directory tree still includes some directories from when it was hosted in a svn repository. _(`/trunk/1.0.0/`)_ can be changed to get rid of some useless nesting.

**Comment by michaelcullum** [comment]
Thanks. Could you make a PR afterwards?

**Comment by erikfrerejean** [comment]
#39 is the pull request ;)

**Comment by michaelcullum** [comment]
Oh right. Its going to have quite a few conflicts with all the changes being made at the moment...

**Comment by erikfrerejean** [comment]
Which is why I suggested for after 1.0.0 ;). But conflicts shouldn't be a big issue, only if one adds files to the current structure you need to account for the new locations for those files.
