### ISSUE TITLE
Required fields

### ISSUE THREAD

**Issue by vinny** [phpBB-Blog/phpBB-Blog#45]
Articles are accepted with all fields blank.

**Comment by michaelcullum** [comment]
hm... I don't think this is much of a bug, just a lack of a feature. I'll put it in for the next version after 1.0.0 (so if validation fails it will be in the next submitted version).

**Comment by vinny** [comment]
The same happens with comments

**Comment by michaelcullum** [comment]
Ok. Just needs a validation for a minimum of 1 character.
