### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by michaelcullum** [phpBB-Blog/phpBB-Blog#47]
David just pointed out some serious issues in the code including 5 queries per blog post on the main blog page (4 blog posts is 20 queries plus all the other queries). He also seems to be putting in variables and making functions static.

As such I doubt it will be ready for validation tomorrow but I'll still try. It should be Saturday at the latest (hopefully).

**Comment by michaelcullum** [comment]
@imkingdavid I just commited some changes to the template variables, adding a variable above the template vars and changed the <code>$config['BLOG_ON'] == 0 to $blog_on_c == 0</code>

**Comment by michaelcullum** [comment]
Those commits got reverted but even so. You might want to merge this into your local copy. ;)

**Comment by michaelcullum** [comment]
Done by the looks of it. Lets get this packaged up.

**Comment by michaelcullum** [comment]
Ah he hadn't finished (I thought you had as it was merged).

**Comment by imkingdavid** [comment]
Yeah, sorry, I was just merging what I had.

**Comment by michaelcullum** [comment]
Merged the last commit in.
