### ISSUE TITLE
Blog Parse Error

### ISSUE THREAD

**Issue by michaelcullum** [phpBB-Blog/phpBB-Blog#52]
<code>Parse error: syntax error, unexpected T_VARIABLE in C:\xampp\htdocs\devqi\boards\blog_gold\blog.php on line 107</code>

Caused by david's code cleanup.

**Comment by michaelcullum** [comment]
#47

**Comment by imkingdavid** [comment]
Missing semicolon on line 106.

**Comment by michaelcullum** [comment]
I found it but I was going out and didn't have time to commit. Thanks.

**Comment by imkingdavid** [comment]
I did some more, but still haven't completely finished. I didn't merge it with the main repo so you didn't think I was done.

I am going to a movie with my brother, so I probably won't get to finish until tomorrow night or monday night at the earliest. But please do test and make sure I'm not missing stuff, if you don't mind.

**Comment by michaelcullum** [comment]
Ok then. I'll post an update in the main topic.
