### ISSUE TITLE
Another Parse error on blog index.

### ISSUE THREAD

**Issue by michaelcullum** [phpBB-Blog/phpBB-Blog#53]
<code>Parse error: syntax error, unexpected T_DOUBLE_ARROW in C:\xampp\htdocs\devqi\boards\blog_gold\blog.php on line 125</code>

**Comment by vinny** [comment]
https://github.com/phpBB-Blog/phpBB-Blog/commit/ff4db4d527b6bfe49740de22620ba5e56bb30e9a
The commit was not complete. Still have errors, the blog index dont display the articles and has the following error when viewing a category:
<code>[phpBB Debug] PHP Notice: in file [ROOT]/blog.php on line 185: Undefined variable: sql
[phpBB Debug] PHP Warning: in file [ROOT]/includes/db/dbal.php on line 543: Missing argument 2 for dbal::sql_build_query(), called in [ROOT]/blog.php on line 185 and defined
[phpBB Debug] PHP Notice: in file [ROOT]/blog.php on line 214: Undefined variable: blog_data
[phpBB Debug] PHP Notice: in file [ROOT]/blog.php on line 215: Undefined variable: blog_data
[phpBB Debug] PHP Notice: in file [ROOT]/blog.php on line 216: Undefined variable: blog_data
[phpBB Debug] PHP Notice: in file [ROOT]/blog.php on line 216: Undefined variable: blog_data</code>
Also dont display any article.

**Comment by michaelcullum** [comment]
I'm not sure what's caused this.

**Comment by michaelcullum** [comment]
Oh and #47

**Comment by michaelcullum** [comment]
Ignore the above, I posted it in the wrong Issue. _embarassed_

**Comment by erikfrerejean** [comment]
This one will be resolved with #58

**Comment by michaelcullum** [comment]
solved
