### ISSUE TITLE
Correct queries

### ISSUE THREAD

**Issue by erikfrerejean** [phpBB-Blog/phpBB-Blog#60]
The queries are slow and a bit of a mess. They should be rewritten to properly join the various tables and there should be looked at whether every query is actually needed and/or can be optimised.

**Comment by michaelcullum** [comment]
@imkingdavid  are you doing this as part of your cleanup?

**Comment by imkingdavid** [comment]
I have cleaned up queries on my own fork, but do not wish to merge it if erik is doing the same on his.

We really should split up these tasks so we don't have so many duplicate or similar fixes.

**Comment by michaelcullum** [comment]
I've spoken to both of you and afaik your both doing different fixes. As a rule of thumb, if you spot something check the other persons branch. Also, try and merge stuff in as soon as you can.

**Comment by michaelcullum** [comment]
IRC?

**Comment by erikfrerejean** [comment]
@imkingdavid, please merge the fixed up queries. So far I've only touched a couple of typo's in them _(missing comma in one and applied a heck that shouldn't be needed anymore)_

**Comment by imkingdavid** [comment]
It'll be later before I can do that because I still have a tad more to do but even before that I have to walk my neighbor's dogs and it's supper time.

**Comment by imkingdavid** [comment]
Okay, so with my latest merge, I don't see any more looped queries but I might have missed something. I still haven't gotten around to doing any testing, but I'll wait until erik merges his fixes to do so.
