### ISSUE TITLE
Debug Error in blog.php

### ISSUE THREAD

**Issue by michaelcullum** [phpBB-Blog/phpBB-Blog#66]
[phpBB Debug] PHP Notice: in file [ROOT]/includes/mods/constants_blog.php on line 12: Undefined variable: table_prefix
[phpBB Debug] PHP Notice: in file [ROOT]/includes/mods/constants_blog.php on line 12: Constant BLOGS_TABLE already defined
[phpBB Debug] PHP Notice: in file [ROOT]/includes/mods/constants_blog.php on line 13: Undefined variable: table_prefix
[phpBB Debug] PHP Notice: in file [ROOT]/includes/mods/constants_blog.php on line 13: Constant BLOG_CMNTS_TABLE already defined
[phpBB Debug] PHP Notice: in file [ROOT]/includes/mods/constants_blog.php on line 14: Undefined variable: table_prefix
[phpBB Debug] PHP Notice: in file [ROOT]/includes/mods/constants_blog.php on line 14: Constant BLOG_CATS_TABLE already defined
[phpBB Debug] PHP Notice: in file [ROOT]/includes/mods/constants_blog.php on line 15: Constant MAX_BLOG_CNT_DISPLAY already defined

in blog.php

**Comment by erikfrerejean** [comment]
This one is fixed with #69, must have missed this report
