### ISSUE TITLE
Won't show blog posts

### ISSUE THREAD

**Issue by michaelcullum** [phpBB-Blog/phpBB-Blog#68]
It shows invalid blog ID but yet they create sucessfully and they don't show on the index.

**Comment by erikfrerejean** [comment]
Same goes for the tags overview `blog.php?action=tag&t=sometag`, the way the tag information is stored makes it pretty hard to query on the tag.

**Comment by michaelcullum** [comment]
I think this is fixed with #69? (I haven't tested)

**Comment by erikfrerejean** [comment]
No #69 only resolves a php notice. The blog queries them self are a bit of a mess, in the tag example the whole "tag" isn't used to filter in the first place.
That said, I haven't had time yet to dive into that but I'm afraid that it won't be a trivial change to get those instances fixed.

**Comment by michaelcullum** [comment]
Seems solved anyway.

**Comment by michaelcullum** [comment]
Something weird is going on, I made a zip from my repo, then installed it. But my board and repo are different. Scrap my last.

**Comment by michaelcullum** [comment]
Fixed but:
SQL ERROR [ mysql4 ]

Unknown column 'ct.cmnt_poster_id' in 'where clause' [1054]

SQL

SELECT c.*, u.user_id, u.username, u.user_colour FROM (phpbb_blog_comments c CROSS JOIN phpbb_users u) WHERE c.cmnt_blog_id = 1 AND u.user_id = ct.cmnt_poster_id LIMIT 10

BACKTRACE

FILE: [ROOT]/includes/db/mysql.php
LINE: 175
CALL: dbal->sql_error()

FILE: [ROOT]/includes/db/mysql.php
LINE: 222
CALL: dbal_mysql->sql_query()

FILE: [ROOT]/includes/db/dbal.php
LINE: 170
CALL: dbal_mysql->_sql_query_limit()

FILE: [ROOT]/blog.php
LINE: 310
CALL: dbal->sql_query_limit()
