### ISSUE TITLE
Blog index not showing the articles

### ISSUE THREAD

**Issue by michaelcullum** [phpBB-Blog/phpBB-Blog#72]
(12:50:30 AM) unknownbliss: its not displaying the blog article
(12:50:34 AM) unknownbliss: but it does say
(12:50:35 AM) unknownbliss: Posted by Guest in on Thu Jan 01, 1970 12:00 am
(12:50:35 AM) unknownbliss: Read the rest of this entry »
(12:50:45 AM) unknownbliss: and the link to read the rest etc.
(12:50:54 AM) imkingdavid: and if you click the link?
(12:50:55 AM) unknownbliss: doesn't have a blog id attatched to it

**Comment by imkingdavid** [comment]
Made _some_ progress on this just now (convering the CROSS JOINs into LEFT JOINs. However, it's still only showing 1 item when there are two.

Also, comments aren't being posted

**Comment by michaelcullum** [comment]
Fixed but the fix is causing #74 so I can't merge it in.

**Comment by michaelcullum** [comment]
Fixed.
