### ISSUE TITLE
When categories are disabled, cannot post new article.

### ISSUE THREAD

**Issue by imkingdavid** [phpBB-Blog/phpBB-Blog#79]
Reported: http://www.phpbb.com/community/viewtopic.php?f=70&t=2104706&start=225#p13124298

I have not confirmed this bug, but I'm not surprised that it's there.

As a workaround, rather than a fix, you can simply only use one category to put all your posts into. _shrug_ Or we can do yet another bugfix release to make that work nicely.

**Comment by michaelcullum** [comment]
Or we could remove the config option?
