### ISSUE TITLE
Issue with custom BBcodes

### ISSUE THREAD

**Issue by michaelcullum** [phpBB-Blog/phpBB-Blog#80]
Reported: http://www.phpbb.com/community/viewtopic.php?p=13124373#p13124373

Unconfirmed and unlikely. Most likely a MOD Clash.

As such I'll mark this as unreproducible and close it unless we can reproduce this.

**Comment by imkingdavid** [comment]
This is a MOD Clash with advanced BBCode, as far as I can tell. I have not tried to reproduce this, but I'm sure if we tried to install the two MODs on the same board, it would pop up.

**Comment by michaelcullum** [comment]
It would be because it makes edits to the bbcodes (which we use from phpBB) but we don't have the edits made to the blog that get made to the posting pages.

**Comment by imkingdavid** [comment]
So are we going to fix this clash?

**Comment by michaelcullum** [comment]
Only once the bugs are fixed first. :P Can you pop on IRC?
