### ISSUE TITLE
When tags are added during posting, they display in cloud but not beneath post

### ISSUE THREAD

**Issue by imkingdavid** [phpBB-Blog/phpBB-Blog#83]
Title says it all.

Reported: http://www.phpbb.com/community/viewtopic.php?f=70&t=2104706&p=13125410#p13125331

**Comment by michaelcullum** [comment]
Do they come up when editing a blog post?

**Comment by vinny** [comment]
<blockquote>Do they come up when editing a blog post?</blockquote>


When editing is fine, just doesnt work when you view a post, only displays <strong>No tags</strong>.
