### ISSUE TITLE
Add a return link when deleting comments

### ISSUE THREAD

**Issue by imkingdavid** [phpBB-Blog/phpBB-Blog#84]
Title says it.

Reported: http://www.phpbb.com/community/viewtopic.php?f=70&t=2104706&p=13125410#p13125331

**Comment by vinny** [comment]
PR: https://github.com/phpBB-Blog/phpBB-Blog/pull/87

David or UB, could you please check the PR?

**Comment by michaelcullum** [comment]
Fixed with #87
