### ISSUE TITLE
Problem with IE 9

### ISSUE THREAD

**Issue by mastum** [phpBB-Blog/phpBB-Blog#85]
Hi, as title ... there is a visual problem with IE 9
phpBB 3.0.10, theme prosilver and only phpBB Blog installed.

http://i39.tinypic.com/vhs189.jpg

Many thanks for this great mod !

**Comment by vinny** [comment]
I believe that CSS isn't applied correctly. Please refresh the prosilver's template.

I'll check the error in IE9 because IE8 works perfectly.

**Comment by vort7u** [comment]
Thanks!
I confirm, the problem is only with IE9

**Comment by michaelcullum** [comment]
@MaFeSa Please refresh the prosilver's template.

**Comment by vort7u** [comment]
Now is ok, sorry!
