### ISSUE TITLE
Graphic problem-{T_THEME_PATH}

### ISSUE THREAD

**Issue by Magastart** [phpBB-Blog/phpBB-Blog#90]
Hi and thank you for this mod.
I have graphics problem.
I use Prospace theme(prosilver theme base) and used menu.html for navbar.
This code is then added to overallheader.html
 .........link href="{T_THEME_PATH} /blog.css"..............

I changed the code and I have tried :
 "href="{T_SUPER_THEME_PATH}/blog.css" 

improved the menu, but the broken category graphic

sorry for my bad english but pict and url are shows.
thank you

**Comment by michaelcullum** [comment]
This is for bug reports, not support. Please get that from http://www.phpbb.com/community/viewtopic.php?f=70&t=2104706

**Comment by Magastart** [comment]
Ok.I am sorry.
